### PR TITLE
Added a custom description function

### PR DESCRIPTION
**Pull request by TroyLDay**
Please consider this addition to support customization of the description at the bottom of the lightbox - fashioned similar to the custom image function.

Changed the gulp task because when I first brought of the file using gulp server, the min file had not been created.

Kind Thanks!

### CODE REVIEW

**Comment by TroyLDay** [comment]
@jfcaiceo , do you foresee working toward a merge of this? Always open to changes...

**Comment by jfcaiceo** [comment]
It looks okay to me. Sorry for the wait, but I have not much time now.

**Comment by TroyLDay** [comment]
Understood...that helps me plan. Thanks!

**Comment by TroyLDay** [comment]
I hope you can find time to push a new version to npm. Thanks again.

**Comment by jfcaiceo** [comment]
I pushed the new version to npm. Thanks for the pull request

**Pull request merged**
